//
//  DestinyResultsViewController.m
//  DestinyNumbers
//
//  Created by burnsoft on 6/7/17.
//  Copyright © 2017 burnsoft. All rights reserved.
//

#import "DestinyResultsViewController.h"

@interface DestinyResultsViewController ()

@end

@implementation DestinyResultsViewController

#pragma mark View Did Load
//When the View first Appears
- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
    self.lblTitle.text = _yourNumber;
    self.txtMeaning.text = _pushMeaning;
    
    UIBarButtonItem *actionButton = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemAction target:self action:@selector(startAction)];
    NSArray *NavArray = [NSArray new];
    NavArray = [[NSArray alloc] initWithObjects:actionButton, nil];
    self.navigationItem.rightBarButtonItems = NavArray;

    [self setBackGroundImage];
    
}

#pragma mark View Did Layout Subviews
//when the screen is reorientated to another angle
-(void) viewDidLayoutSubviews
{
    [super viewDidLayoutSubviews];
    [self setBackGroundImage];
}

#pragma mark Memory Warning
//actions to take when a memory warning is issued
- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}

#pragma mark Set Background Image
//set the background image of the view
-(void) setBackGroundImage
{
    UIGraphicsBeginImageContext(self.view.frame.size);
    [[UIImage imageNamed:@"background.jpg"] drawInRect:self.view.bounds];
    UIImage *image = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    
    self.view.backgroundColor = [UIColor colorWithPatternImage:image];
}

#pragma mark Start Action Sheet
//start the action sheet process and gather the data to send to the ActionClass
-(void) startAction
{
    NSString *rawText = [NSString stringWithFormat:@"%@\n\n %@\n\n\n\nGenerated by the Destiny Numbers App of iOS",self.yourNumber,self.pushMeaning];
    
    NSArray *ActionObjects = @[rawText];
    UIActivityViewController *controller = [[UIActivityViewController alloc] initWithActivityItems:ActionObjects applicationActivities:nil];
    NSString *emailSubject = [NSString stringWithFormat:@"%@!",self.yourNumber];
    [controller setValue:emailSubject forKey:@"subject"];
    
    //. On iPad, you must present the view controller in a popover. On iPhone and iPod touch, you must present it modally.
    
    if ([[UIDevice currentDevice] userInterfaceIdiom] == UIUserInterfaceIdiomPhone) {
        //iPhone, present activity view controller as is.
        [self presentViewController:controller animated:YES completion:^{}];
    }
    else
    {
        //iPad, present the view controller inside a popover.
        self.popoverPresentationController.permittedArrowDirections = UIPopoverArrowDirectionRight;
        self.popoverPresentationController.sourceView = self.view;
        
        [self presentViewController:controller animated:YES completion:^{}];
        UIPopoverPresentationController *popController = [controller popoverPresentationController];
        popController.permittedArrowDirections = UIPopoverArrowDirectionAny;
        controller.popoverPresentationController.sourceView = self.view;
    }
    
}


@end
